### ISSUE TITLE
Similar Repos

### ISSUE THREAD

**Issue by GabrielLin** [venom1270/essay-grading-util#1]
Great work!. Could you please tell me what are the differences between this repo and https://github.com/venom1270/essay-grading ? Thanks.

**Comment by venom1270** [comment]
Thanks! This is an utility repo I use to store my tests and other random stuff, while https://github.com/venom1270/essay-grading
contains the Orange widget add-on for essay grading. 
Originally I had put everything in the essay-grading repo but changed it later to conform to Orange add-on repo structure.

**Comment by GabrielLin** [comment]
Thanks for your reply. So, if I do not use Orange, if it enough for me to just study this repo for all your ideas about AES?

**Comment by venom1270** [comment]
No, you'd have to study the essay-grading repo. It's actually based on this thesis: http://eprints.fri.uni-lj.si/4133/1/63120364-KAJA_ZUPANC-Semanti%C4%8Dno_usmerjeno_avtomatsko_ocenjevanje_esejev.pdf
so you could study that instead.

**Comment by GabrielLin** [comment]
OK. Got it. Thanks.
